export const HTTP_CONSTANTS = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

export const ROUTE_TYPES = {
  PUBLIC: 'PUBLIC',
  PROTECTED: 'PROTECTED',
};

export const ROUTE_CONSTANTS = {
  ROOT: '/',
  DASHBOARD: '/dashboard',
};

