export const AAD_ENUM = {
  ADO_ACCESSTOKEN: 'ADO-ACCESS-TOKEN',

  ADO_IDTOKEN: 'ADO-ID-TOKEN',

  ADO_REFRESHTOKEN: 'ADO-REFRESH-TOKEN',

  ADO_EXPIRESON: 'ADO-EXPIRESON',

  ADO_ACCOUNT: 'ADO-ACCOUNT',

  ADO_TOKEN_TYPE: 'ADO-TOKEN-TYPE',

  ADO_ROLE: 'ADO_ROLE',
};
