export const dashboardActionTypes = {
    GET_DASHBOARD_STATS: "GET_DASHBOARD_STATS",
    GET_SYSTEM_DATA_QUESTION_TYPES: "GET_SYSTEM_DATA_QUESTION_TYPES",
    GET_SYSTEM_DATA_QUESTIONS: "GET_ALL_QUESTIONS",
    SET_DASHBOARD_STATS: "SET_DASHBOARD_STATS",
    SET_SYSTEM_DATA_QUESTION_TYPES: "SET_SYSTEM_DATA_QUESTION_TYPES",
    SET_SYSTEM_DATA_QUESTIONS: "SET_SYSTEM_DATA_QUESTIONS",
    SET_DASHBOARD_STATS_FAILURE: "SET_DASHBOARD_STATS_FAILURE",
    SET_SYSTEM_DATA_QUESTION_TYPES_FAILURE: "SET_SYSTEM_DATA_QUESTION_TYPES_FAILURE",
    SET_SYSTEM_DATA_QUESTIONS_FAILURE: "SET_SYSTEM_DATA_QUESTIONS_FAILURE",
};

export const getDashboardStats = () => ({ type: dashboardActionTypes.GET_DASHBOARD_STATS });
export const getSystemDataQuestionTypes = () => ({ type: dashboardActionTypes.GET_SYSTEM_DATA_QUESTION_TYPES });
export const getSystemDataQuestions = () => ({ type: dashboardActionTypes.GET_SYSTEM_DATA_QUESTIONS });